#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Analyse the regressors for a movie that were generated by 'generate_VGG_weights

Calculate the following properties:
    Luminance
    Complexity
    VGG (max pooling for layers)

Requires openCV and Keras 

Created by C Ellis 5/23/18
"""

import numpy as np
import matplotlib.pyplot as plt
from pylab import *
#import skimage.measure
import sys
import os
import math
from sklearn.decomposition import PCA, FastICA
from brainiak.utils import fmrisim as sim

# Specify the regressor file to be loaded in:
if len(sys.argv) > 1:
    regressor_file = sys.argv[1]

if len(sys.argv) > 2:
    tr_duration = float(sys.argv[2])
else:
    tr_duration = 2
    
if len(sys.argv) > 3:
    output_name = sys.argv[3] 
else:
    output_name = './'

# If this is zero then you are creating an RSA as the output. If it is above zero then you will use that many components to create a PCA model and output that as the numpy matrix
if len(sys.argv) > 4:
    pca_components = int(sys.argv[4])
else:
    pca_components = 0 

# Do you want to output an RSA matrix (1) or a regressor file (0)?
if len(sys.argv) > 5:
    output_rsa = int(sys.argv[5])
else:
    output_rsa = 1   
    
# Do you want to convolve the vector across time (Align the unit activity for each frame and then convolve)        
if len(sys.argv) > 6:
    convolve_regressor = int(sys.argv[6])
else:
    convolve_regressor = 0  

# What is the frame rate of the movie?    
if len(sys.argv) > 7:
    fps = int(sys.argv[7])
else:
    fps = 24
    
# Trim the unit activity to get rid of edge effects (what Long 2019 does)    
if len(sys.argv) > 8:    
    trim_prct = int(sys.argv[8])
else:
    trim_prct = 0    
    
    
# Set up how the data is being preprocessed
concatenate_or_average = 0 # Do you want to concatenate all frames in a TR or just average them. If doing PCA without convolution you should average them
downsample_rsa = 0  # When do you want to do the frame downsampling? After the RSA is made (1) or before (0). If concatenate_or_average == 0 then this will be ignored
scale_convolution = False  # Do you want the max of all regressors to be 1. This means that if some regressors are different in importance, this will be ignored

# Do you want to average all of the pixels in a filter (only for convolutional layers)?
if output_name.find('av_filter') > 0:
    average_filters = 1
    print('Averaging within filters to remove spatial information')
else:
    average_filters = 0 

if pca_components != 0 and concatenate_or_average == 1 and convolve_regressor == 0:
    print('You are running PCA without convolution and you are concatenating the frames for each TR. This means you are going to have many more components than you expect')

# Check if this is vgg or inception (not luminance or compression)
is_vgg = regressor_file[regressor_file.rfind('/'):].find('vgg')
is_inc = regressor_file[regressor_file.rfind('/'):].find('inc')

print('Analyze %s' % regressor_file)

reg_vec = np.load(regressor_file)

# What is the name of the layer
layer_name = regressor_file[regressor_file.find('/vgg_') + 5:regressor_file.find('/vgg_') + 8]

# What is the dimensionality of the first 5 pooling layers of 
layer_dims = {'b1p': 112, 'b2p': 56, 'b3p': 28, 'b4p': 14, 'b5p': 7}

# If you want to trim anything, then reshape the data to be the size that is appropriate for the file and then zero out the values
if trim_prct > 0:
    
    # How much should you trim from the actual filter
    trim_amount = int(np.round(layer_dims[layer_name] * trim_prct / 100))

    # how many filters are there?
    filter_num = int(reg_vec.shape[1] / (layer_dims[layer_name] ** 2))
    
    # Reshape the vector into matrices
    reg_mat = np.copy(reg_vec.reshape(reg_vec.shape[0], layer_dims[layer_name], layer_dims[layer_name], filter_num))

    # Trim the data
    reg_mat[:, :trim_amount, :, :] = 0
    reg_mat[:, :, :trim_amount, :] = 0
    reg_mat[:, layer_dims[layer_name]-trim_amount:, :, :] = 0
    reg_mat[:, :, layer_dims[layer_name]-trim_amount:, :] = 0

    # Remake the data
    reg_vec = reg_mat.reshape(reg_mat.shape[0], int(np.prod(reg_mat.shape[1:])))

# If 1, then average the filter spatial information within filter for each frame. Thus the matrices represent the expression of each filter type over time    
if average_filters == 1 and layer_name.find('fc') == -1:
    
    # Get the dimensionality of the data
    dim = layer_dims[layer_name]
    filter_num = int(reg_vec.shape[1] / (dim ** 2))
    
    # Make the data filter by time
    reg_mat = reg_vec.reshape(reg_vec.shape[0], dim, dim, filter_num)
    
    # Create an RSA that averages the feature values per filter
    temp_reg_vec = np.zeros((reg_vec.shape[0], filter_num))
    for filter_counter in range(filter_num):

        reshaped_data = reg_mat[:, :, :, filter_counter].reshape(reg_mat.shape[0], dim ** 2)
        temp_reg_vec[:, filter_counter] = np.mean(reshaped_data, 1)
    
    # Save the data
    reg_vec = temp_reg_vec
     
print('Data has dim: %d by %d' % (reg_vec.shape[0], reg_vec.shape[1]))

# Convert the regressor in to a frame by unit matrix
#if downsample_rsa == 1:   

# If it is to be convolved then do so here
if is_vgg == 1 or is_inc == 1:
    
    # Transform the framewise unit activity into PCA space (frame by component) or ICA 
    if pca_components != 0:     
        
        if pca_components > 0:
            # If you are creating a PCA of the data then do so here
            model = PCA(n_components=pca_components)
        else:
            # If you are creating a PCA of the data then do so here
            model = FastICA(n_components=abs(pca_components), max_iter=10000)

        # What are the PCA weights
        reg_vec = model.fit_transform(reg_vec)
        
        # Pull out the component by feature loadings
        component_loadings = model.components_
        
        if pca_components > 0:
            # How much variance is explained
            explained_variance = np.sum(model.explained_variance_ratio_)

            print('Explained variance for %s pca: %0.3f, top component: %0.3f' % (regressor_file, explained_variance, model.explained_variance_ratio_[0]))
    
    ## Reduce the dimensionality of the data to be TR by feature, either by convolution, averaging or concatenating the features across time
    if convolve_regressor == 1:

        reg_vec = sim.convolve_hrf(reg_vec, tr_duration, scale_function=scale_convolution, temporal_resolution=fps)
    else:    
        
        # Reshape the regressor to be a tr by unit feature matrix by concatenating all the frames within a TR into a long list.
        frame_num = reg_vec.shape[0]
        tr_number = int(np.ceil((frame_num / fps) / tr_duration))  # How many TRs are there?
        frame_window_size = int(np.round(fps * tr_duration))
        
        # Preset the array
        if concatenate_or_average == 1:
            temp_reg_vec = np.zeros((tr_number, len((reg_vec[0:int(frame_window_size), :]).flatten())))
        else:
            temp_reg_vec = np.zeros((tr_number, reg_vec.shape[1]))
            
        for tr in range(tr_number):

            # Get the lower and upper index
            l_idx = int(tr * frame_window_size)
            u_idx = int((tr + 1) * frame_window_size)
            if u_idx >= frame_num:
                u_idx = int(frame_num - 1)  # Bound

            # Store the TR
            if concatenate_or_average == 1:
                temp_reg_vec[tr, :] = reg_vec[l_idx:u_idx, :].flatten()
            else:
                temp_reg_vec[tr, :] = np.mean(reg_vec[l_idx:u_idx, :], 0)

        # Rewrite
        reg_vec = temp_reg_vec
        
        print('Reshaped the reg_vec to now be %d by %d' % (reg_vec.shape[0], reg_vec.shape[1]))

# Remove any columns containing nans, since they reflect units 'outside of the mask'
incl_columns = np.mean(np.isnan(reg_vec), 0) == 0
reg_vec = reg_vec[:, incl_columns]

# Only analyze the VGG layer
if is_vgg == 1 or is_inc == 1:

    # If you are outputting the RSA data then do so here
    if output_rsa == 1:

        # Correlate every row with every other row
        regressor_rsa = np.corrcoef(reg_vec)

        # Now downsample the RSA if appropriate
        if downsample_rsa == 1:

            # Take the mean of the matrix for blocks of the specified size (tiles the matrix and averages in each tile, thus has a problem with the diagonal)
            regressor_rsa_ds = skimage.measure.block_reduce(regressor_rsa,
                                                            (frame_window_size,frame_window_size),
                                                            np.mean)

            # Trim the excess off to match the other version
            regressor_rsa_ds = regressor_rsa_ds[:tr_number, :tr_number]

            # Store the data
            np.save(output_name, regressor_rsa_ds)
        else:
            # Store the data
            np.save(output_name, regressor_rsa)

    else:
        
        # Save the data as a regressor
        print('Saving the time course of data, not the RSA')
        
        # Save the output
        np.save(output_name, reg_vec)
        
        # Save the component loadings
        np.save(output_name[:-4] + '_loadings.npy', component_loadings)
        
        # Create a TR by TR similarity matrix with this data
        #rsa_mat = np.corrcoef(reg_vec)

else:
    
    # Either just average the luminance or convolve it
    if convolve_regressor == 0:
        # Generate a mean within TR
        regressor_tr = np.mean(reg_vec, 1)

        # Store the data
        np.save(output_name, regressor_tr)
    
    else:

        # Convolve the regressor
        reg_vec = reg_vec.flatten() # String the frames together
        reg_vec = reg_vec.reshape((len(reg_vec), 1))
        regressor_convolved = sim.convolve_hrf(reg_vec, tr_duration, temporal_resolution=fps)
        np.save(output_name, regressor_convolved)

print('Finished')
